base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_4bit: true
load_in_8bit: false

datasets:
  - path: /workspace/data/postman_finetune_dataset.json
    type: alpaca
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

val_set_size: 0.0
output_dir: ./outputs/tinyllama-out

adapter: qlora
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

sequence_len: 2048
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 6

optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002
weight_decay: 0.0
warmup_ratio: 0.1

bf16: auto
tf32: true
flash_attention: true

logging_steps: 1
saves_per_epoch: 1
